apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: service2:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
                  memory: "128Mi"
                  cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    run: service2
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: service2