name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # workflow_dispatch:
  #   inputs:
  #     dbe-go-server-tags:
  #       description: 'lukeroy/dbe-go-server Tag'     
  #       required: true
  #       default: ''
  #     dbe-py-server-tag:
  #       description: 'lukeroy/dbe-py-server Tag'     
  #       required: true
  #       default: '' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push lukeroy/dbe-py-server
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: flask_server
          push: true
          tags: lukeroy/dbe-py-server:latest

      - name: Build and push lukeroy/dbe-go-server
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: go_server
          push: true
          tags: lukeroy/dbe-go-server:latest 

      - name: Build and push lukeroy/dbe-simple-python
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: simple_python
          push: true
          tags: lukeroy/dbe-simple-python:latest 

      - name: Build and push lukeroy/dbe-learn-linux
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: linux
          push: true
          tags: lukeroy/dbe-learn-linux:latest 
