name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      dbe-go-server-tags:
        description: 'Tags '     
        required: true
        default: 'latest'
      dbe-py-server-tag:
        description: 'Tags'     
        required: true
        default: 'latest' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push lukeroy/dbe-py-server
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: flask_server
          push: true
          tags: lukeroy/dbe-py-server:${{ github.event.inputs.dbe-py-server-tags }}

      - name: Build and push lukeroy/dbe-go-server
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: go_server
          push: true
          tags: lukeroy/dbe-go-server:${{ github.event.inputs.dbe-go-server-tags }}
